# Generated by Django 4.0.2 on 2022-02-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(help_text='Mis. Pendeteksi Banjir', max_length=220, verbose_name='Nama')),
                ('tipe', models.CharField(blank=True, help_text='Mis. Arduino Uno', max_length=100, null=True, verbose_name='Tipe')),
                ('device_id', models.UUIDField(default=uuid.UUID('959b1311-3b1a-49a9-af6a-169f4d34fe2b'), editable=False)),
                ('lokasi', models.TextField(help_text='Isi dengan alamat dimana perangkat tsb dipasang.', verbose_name='Lokasi')),
                ('batas_normal', models.FloatField(default=0)),
                ('batas_waspada', models.FloatField(default=0)),
                ('batas_siaga', models.FloatField(default=0)),
                ('batas_awas', models.FloatField(default=0)),
                ('pemilik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jarak', models.FloatField(help_text='Jarak perangkat ke air (centimeter)')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'waspada'), (2, 'siaga'), (3, 'awas')], default=0)),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perangkat.perangkat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
