# Generated by Django 4.0.2 on 2022-02-23 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataseries',
            old_name='alat',
            new_name='perangkat',
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('f0170f02-7c70-4c39-9265-54ccbf2af5db'), editable=False),
        ),
    ]
