# Generated by Django 4.0.2 on 2022-02-28 00:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0002_rename_alat_dataseries_perangkat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='batas_awas',
            field=models.FloatField(default=0, help_text='Diisi dalam satuan centimeter (cm)'),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='batas_normal',
            field=models.FloatField(default=250, help_text='Diisi dalam satuan centimeter (cm)'),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='batas_siaga',
            field=models.FloatField(default=0, help_text='Diisi dalam satuan centimeter (cm)'),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='batas_waspada',
            field=models.FloatField(default=0, help_text='Diisi dalam satuan centimeter (cm)'),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('948e929d-6b41-482a-b619-12a2d587182d'), editable=False),
        ),
    ]
