# Generated by Django 4.0.2 on 2022-03-23 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0004_alter_perangkat_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perangkat',
            name='beep_alert',
            field=models.BooleanField(default=True, help_text='Bunyikan alert pada perangkat'),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('15044af2-179e-4920-a418-29fff759f246'), editable=False),
        ),
    ]
