# Generated by Django 4.0.2 on 2022-03-24 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0005_perangkat_beep_alert_alter_perangkat_device_id'),
    ]

