# Generated by Django 4.0.2 on 2022-03-24 07:36

from django.db import migrations, models
import location_field.models.plain
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0005_perangkat_beep_alert_alter_perangkat_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('271758f8-45ab-4aca-9f72-bba3dd3a078a'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=location_field.models.plain.PlainLocationField(help_text='Isi dengan alamat dimana perangkat tsb dipasang.', max_length=63),
        ),
    ]
