# Generated by Django 4.0.2 on 2022-03-24 09:44

from django.db import migrations, models
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0006_alter_perangkat_device_id_alter_perangkat_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('95a22987-d823-4850-bc36-38b394adb707'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(help_text='Isi dengan alamat dimana perangkat tsb dipasang.', map_attrs={}),
        ),
    ]
