# Generated by Django 4.0.2 on 2022-03-24 09:53

from django.db import migrations, models
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0007_alter_perangkat_device_id_alter_perangkat_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('36fe1d37-d39b-47b2-a870-107ed8ad4005'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(default='0,0', map_attrs={'center': [17.031645, 51.106715], 'marker_color': 'blue'}),
        ),
    ]
