# Generated by Django 4.0.2 on 2022-03-24 10:03

from django.db import migrations, models
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0008_alter_perangkat_device_id_alter_perangkat_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('d0768bed-5acb-4604-bcb6-fec3a7569745'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(default='0,0', map_attrs={'center': [51.505, -0.09], 'marker_color': 'blue'}),
        ),
    ]
