# Generated by Django 4.0.2 on 2022-03-24 10:11

from django.db import migrations, models
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0009_alter_perangkat_device_id_alter_perangkat_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('650bc5f3-a4bc-47a0-b13b-36a8a0b2e89a'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [51.505, -0.09], 'marker_color': 'blue', 'zoom': 2}),
        ),
    ]
