# Generated by Django 4.0.4 on 2022-05-10 15:55

from django.db import migrations, models
import mapbox_location_field.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('perangkat', '0010_alter_perangkat_device_id_alter_perangkat_lokasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perangkat',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('dc89ec59-8047-4b4c-a22c-184954691d5f'), editable=False),
        ),
        migrations.AlterField(
            model_name='perangkat',
            name='lokasi',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [115.64105190308777, -0.5163104314298437], 'marker_color': 'blue', 'zoom': 2}),
        ),
    ]
