# Generated by Django 4.0.2 on 2022-02-23 02:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(help_text='Mis. Pendeteksi Banjir', max_length=220, verbose_name='Nama')),
                ('tipe', models.CharField(blank=True, help_text='Mis. Arduino Uno', max_length=100, null=True, verbose_name='Tipe')),
                ('unique_id', models.UUIDField(default=uuid.UUID('a0199432-5d35-4422-9e45-69493cbdb61e'), editable=False)),
                ('lokasi', models.TextField(help_text='Isi dengan alamat dimana alat tsb dipasang.', verbose_name='Lokasi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
