# Generated by Django 4.0.2 on 2022-02-23 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='pemilik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alat',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('5fa5da72-41f4-47e6-8d2c-3b404091d121'), editable=False),
        ),
        migrations.CreateModel(
            name='DataSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jarak', models.FloatField(help_text='Jarak alat ke air')),
                ('status', models.CharField(choices=[(0, 'normal'), (1, 'waspada'), (2, 'siaga'), (3, 'awas')], default=0, max_length=20)),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alat.alat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
