# Generated by Django 4.0.2 on 2022-02-23 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0002_alat_pemilik_alter_alat_unique_id_dataseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alat',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('543d152c-8afa-4141-b836-dec28437acad'), editable=False),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'waspada'), (2, 'siaga'), (3, 'awas')], default=0),
        ),
    ]
