# Generated by Django 4.0.2 on 2022-02-23 03:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alat', '0003_alter_alat_unique_id_alter_dataseries_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='alat',
            name='batas_awas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alat',
            name='batas_normal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alat',
            name='batas_siaga',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alat',
            name='batas_waspada',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='alat',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('eb31a18f-ad8c-43b4-90ac-54ef56611e34'), editable=False),
        ),
        migrations.AlterField(
            model_name='dataseries',
            name='jarak',
            field=models.FloatField(help_text='Jarak alat ke air (centimeter)'),
        ),
    ]
